-- Apply only to a dedicated learning database; this file creates no database or login.
CREATE TABLE users (id uuid PRIMARY KEY, email text NOT NULL, active boolean NOT NULL DEFAULT true, password_record jsonb, security_version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX users_email_unique ON users(lower(email));
CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL, sso_required boolean NOT NULL DEFAULT false);
CREATE TABLE workspaces (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations, name text NOT NULL, UNIQUE(organization_id,id));
CREATE TABLE identity_providers (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations, protocol text NOT NULL CHECK(protocol IN ('oidc','saml')), issuer text NOT NULL, config jsonb NOT NULL, enabled boolean NOT NULL DEFAULT true, UNIQUE(organization_id,id), UNIQUE(organization_id,issuer));
CREATE TABLE external_identities (provider_id uuid NOT NULL REFERENCES identity_providers, subject text NOT NULL, user_id uuid NOT NULL REFERENCES users, PRIMARY KEY(provider_id,subject));
CREATE TABLE memberships (organization_id uuid NOT NULL REFERENCES organizations, user_id uuid NOT NULL REFERENCES users, role text NOT NULL CHECK(role IN ('viewer','editor','admin','owner')), active boolean NOT NULL DEFAULT true, version bigint NOT NULL DEFAULT 0, PRIMARY KEY(organization_id,user_id));
CREATE INDEX memberships_user_org ON memberships(user_id,organization_id) WHERE active;
CREATE TABLE documents (organization_id uuid NOT NULL, id uuid NOT NULL, workspace_id uuid NOT NULL, owner_id uuid NOT NULL, title text NOT NULL, PRIMARY KEY(organization_id,id), FOREIGN KEY(organization_id,workspace_id) REFERENCES workspaces(organization_id,id), FOREIGN KEY(organization_id,owner_id) REFERENCES memberships(organization_id,user_id));
CREATE TABLE roles (organization_id uuid NOT NULL REFERENCES organizations, id uuid NOT NULL, name text NOT NULL, PRIMARY KEY(organization_id,id), UNIQUE(organization_id,name));
CREATE TABLE permissions (name text PRIMARY KEY);
CREATE TABLE role_permissions (organization_id uuid NOT NULL, role_id uuid NOT NULL, permission text NOT NULL REFERENCES permissions, PRIMARY KEY(organization_id,role_id,permission), FOREIGN KEY(organization_id,role_id) REFERENCES roles(organization_id,id));
CREATE TABLE role_assignments (organization_id uuid NOT NULL, user_id uuid NOT NULL, role_id uuid NOT NULL, PRIMARY KEY(organization_id,user_id,role_id), FOREIGN KEY(organization_id,user_id) REFERENCES memberships, FOREIGN KEY(organization_id,role_id) REFERENCES roles(organization_id,id));
CREATE TABLE sessions (secret_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users, csrf_hash text NOT NULL, auth_time timestamptz NOT NULL, last_seen timestamptz NOT NULL, absolute_expires timestamptz NOT NULL, revoked_at timestamptz, security_version bigint NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE oauth_clients (id text PRIMARY KEY, secret_hash text, redirect_uris text[] NOT NULL, scopes text[] NOT NULL, public boolean NOT NULL, CHECK(NOT public OR secret_hash IS NULL));
CREATE TABLE authorization_grants (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users, client_id text NOT NULL REFERENCES oauth_clients, organization_id uuid NOT NULL, scopes text[] NOT NULL, revoked_at timestamptz, FOREIGN KEY(organization_id,user_id) REFERENCES memberships);
CREATE TABLE refresh_families (id uuid PRIMARY KEY, grant_id uuid NOT NULL REFERENCES authorization_grants, absolute_expires timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE refresh_tokens (secret_hash text PRIMARY KEY, family_id uuid NOT NULL REFERENCES refresh_families, used_at timestamptz, issued_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE authorization_codes (secret_hash text PRIMARY KEY, grant_id uuid NOT NULL REFERENCES authorization_grants, redirect_uri text NOT NULL, pkce_challenge text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE api_credentials (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations, principal_id text NOT NULL, secret_hash text NOT NULL, audience text NOT NULL, scopes text[] NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE signing_keys (kid text PRIMARY KEY, algorithm text NOT NULL, public_jwk jsonb NOT NULL, kms_reference text NOT NULL, activated_at timestamptz NOT NULL, retired_at timestamptz);
CREATE TABLE invitations (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations, email text NOT NULL, role text NOT NULL CHECK(role IN ('viewer','editor','admin')), secret_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, accepted_at timestamptz);
CREATE TABLE mfa_credentials (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users, type text NOT NULL, credential_id text UNIQUE, public_key bytea, encrypted_totp_secret bytea, sign_count bigint NOT NULL DEFAULT 0);
CREATE TABLE audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, time timestamptz NOT NULL DEFAULT now(), organization_id uuid, actor_id text, event text NOT NULL, outcome text NOT NULL, details jsonb NOT NULL);
CREATE INDEX audit_org_time ON audit_events(organization_id,time DESC);
CREATE TABLE scim_resources (organization_id uuid NOT NULL REFERENCES organizations, id uuid NOT NULL, external_id text, kind text NOT NULL CHECK(kind IN ('User','Group')), user_id uuid REFERENCES users, data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, PRIMARY KEY(organization_id,id));
CREATE INDEX scim_external ON scim_resources(organization_id,external_id);
CREATE TABLE scim_group_members (organization_id uuid NOT NULL, group_id uuid NOT NULL, member_id uuid NOT NULL, PRIMARY KEY(organization_id,group_id,member_id), FOREIGN KEY(organization_id,group_id) REFERENCES scim_resources(organization_id,id), FOREIGN KEY(organization_id,member_id) REFERENCES scim_resources(organization_id,id));
CREATE TABLE provisioning_state (organization_id uuid NOT NULL REFERENCES organizations, connector_id text NOT NULL, cursor text, last_success timestamptz, retry_after timestamptz, PRIMARY KEY(organization_id,connector_id));
CREATE TABLE verified_domains (domain text PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations, verified_at timestamptz NOT NULL);
