#!/usr/bin/env python3
"""Validate and render the learning catalog. Python 3.10+, standard library only.

No lab code is executed and no dependencies are installed by this tool.
"""
import argparse
import html
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'catalog/topics.json'
SLUG = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
LEVELS = ['Intuition', 'Fundamentals', 'Small implementation', 'Internals',
          'Production architecture', 'Integrated build', 'Real implementations', 'Research']
HEADER = '<!-- Generated by scripts/lab.py from catalog/topics.json. Do not edit by hand. -->'


def load_catalog():
    return json.loads(CATALOG.read_text(encoding='utf-8'))


def validate(data):
    errors, labs = [], []

    def fail(message):
        errors.append(message)

    def array(value, context):
        if not isinstance(value, list):
            fail(f'{context}: expected an array')
            return []
        return value

    def records(value, context):
        result = []
        for record in array(value, context):
            if isinstance(record, dict):
                result.append(record)
            else:
                fail(f'{context}: expected object records')
        return result

    def text(value, context):
        if not isinstance(value, str) or not value.strip():
            fail(f'{context}: expected nonempty text')
            return False
        return True

    def identity(record, context):
        value = record.get('id')
        if not isinstance(value, str) or not SLUG.fullmatch(value):
            fail(f'{context}: invalid kebab-case ID')
            return None
        return value

    def path(value, context, base=ROOT):
        if not isinstance(value, str) or not value or Path(value).is_absolute():
            fail(f'{context}: expected a relative path')
            return None
        result = (base / value).resolve()
        if not result.is_relative_to(ROOT):
            fail(f'{context}: path leaves the repository')
            return None
        return result

    if not isinstance(data, dict) or type(data.get('schema_version')) is not int or data['schema_version'] != 1:
        return ['Catalog must be an object with schema_version 1'], []
    domains = {}
    for domain in records(data.get('domains'), 'domains'):
        did = identity(domain, 'domain')
        if did is None:
            continue
        if did in domains:
            fail(f'Duplicate domain ID: {did}')
        text(domain.get('title'), f'{did}.title')
        text(domain.get('purpose'), f'{did}.purpose')
        groups = set()
        for group in records(domain.get('groups'), f'{did}.groups'):
            gid = identity(group, f'{did} group')
            text(group.get('title'), f'{did} group title')
            if gid in groups:
                fail(f'{did}: duplicate group {gid}')
            if gid:
                groups.add(gid)
        domains[did] = groups

    topics, topic_paths, lab_ids, manifest_paths = {}, set(), set(), set()
    for topic in records(data.get('topics'), 'topics'):
        tid = identity(topic, 'topic')
        if tid is None:
            continue
        if tid in topics:
            fail(f'Duplicate topic ID: {tid}')
        topics[tid] = topic
        for key in ['title', 'question']:
            text(topic.get(key), f'{tid}.{key}')
        did, group = topic.get('domain'), topic.get('group')
        if not isinstance(did, str) or did not in domains:
            fail(f'{tid}: unknown domain {did}')
        elif not isinstance(group, str) or group not in domains[did]:
            fail(f'{tid}: unknown group {group}')
        status = topic.get('status')
        if status not in ('planned', 'seed', 'growing', 'reference'):
            fail(f'{tid}: invalid status')
        home = path(topic.get('path'), f'{tid}.path')
        if home:
            if home in topic_paths:
                fail(f'{tid}: duplicate topic path')
            topic_paths.add(home)
            if not home.is_relative_to(ROOT / 'domains' / str(did)) or home == ROOT / 'domains' / str(did):
                fail(f'{tid}: topic must live under domains/{did}/')
            if status != 'planned' and not (home / 'README.md').is_file():
                fail(f'{tid}: active topic has no README')
        for key in ['tags', 'prerequisites', 'related']:
            values = array(topic.get(key), f'{tid}.{key}')
            strings = [x for x in values if isinstance(x, str)]
            if len(strings) != len(values) or any(not x.strip() for x in strings):
                fail(f'{tid}.{key}: expected nonempty strings')
            if len(set(strings)) != len(strings):
                fail(f'{tid}.{key}: duplicate values')
        seen_levels = set()
        for milestone in records(topic.get('milestones', []), f'{tid}.milestones'):
            level = milestone.get('level')
            if type(level) is not int or level not in range(8):
                fail(f'{tid}: milestone level must be 0..7')
            elif level in seen_levels:
                fail(f'{tid}: duplicate milestone level {level}')
            else:
                seen_levels.add(level)
            text(milestone.get('outcome'), f'{tid} milestone outcome')
            state = milestone.get('state')
            if state not in ('planned', 'available', 'verified'):
                fail(f'{tid}: invalid milestone state')
            artifacts = array(milestone.get('artifacts'), f'{tid} milestone artifacts')
            if state in ('available', 'verified') and not artifacts:
                fail(f'{tid}: available/verified milestone requires evidence artifacts')
            for artifact in artifacts:
                target = path(artifact, f'{tid} milestone artifact')
                if target and not target.exists():
                    fail(f'{tid}: missing artifact {artifact}')
        for manifest in array(topic.get('labs', []), f'{tid}.labs'):
            target = path(manifest, f'{tid} lab manifest')
            if not target:
                continue
            if target in manifest_paths:
                fail(f'{tid}: lab manifest registered more than once')
            manifest_paths.add(target)
            if home and not target.is_relative_to(home):
                fail(f'{tid}: lab manifest must live in its owning topic')
            if status == 'planned':
                fail(f'{tid}: a registered lab needs an active topic')
            try:
                lab = json.loads(target.read_text(encoding='utf-8'))
            except (OSError, ValueError) as exc:
                fail(f'{tid}: cannot read lab manifest: {exc}')
                continue
            if not isinstance(lab, dict):
                fail(f'{tid}: lab manifest must be an object')
                continue
            lid = identity(lab, f'{tid} lab')
            if lid in lab_ids:
                fail(f'Duplicate lab ID: {lid}')
            if lid:
                lab_ids.add(lid)
            if type(lab.get('schema_version')) is not int or lab['schema_version'] != 1 or lab.get('topic') != tid:
                fail(f'{tid}: wrong lab schema version or topic ownership')
            text(lab.get('title'), f'{tid} lab title')
            limitations = array(lab.get('limitations'), f'{tid} lab limitations')
            if not limitations:
                fail(f'{tid}: lab must state its limitations')
            for limitation in limitations:
                text(limitation, f'{tid} lab limitation')
            entry = path(lab.get('entry'), f'{tid} lab entry', target.parent)
            if entry and (not entry.is_file() or entry.suffix != '.html'):
                fail(f'{tid}: lab entry must be an existing HTML file')
            if 'model' in lab:
                model = path(lab['model'], f'{tid} lab model', target.parent)
                if model and not model.is_file():
                    fail(f'{tid}: missing model')
            if entry:
                labs.append({**lab, 'entry': entry.relative_to(ROOT).as_posix(), 'manifest': manifest})

    for tid, topic in topics.items():
        for key in ['prerequisites', 'related']:
            values = topic.get(key)
            if not isinstance(values, list):
                continue
            for other in values:
                if not isinstance(other, str):
                    continue
                if other not in topics:
                    fail(f'{tid}.{key}: unknown topic {other}')
                if other == tid:
                    fail(f'{tid}.{key}: self-link')

    colors = {}

    def visit(tid, chain):
        if colors.get(tid) == 1:
            fail('Prerequisite cycle: ' + ' -> '.join(chain + [tid]))
            return
        if colors.get(tid) == 2:
            return
        colors[tid] = 1
        dependencies = topics[tid].get('prerequisites')
        for dependency in dependencies if isinstance(dependencies, list) else []:
            if isinstance(dependency, str) and dependency in topics:
                visit(dependency, chain + [tid])
        colors[tid] = 2

    for tid in topics:
        visit(tid, [])
    tracks = set()
    for track in records(data.get('tracks'), 'tracks'):
        track_id = identity(track, 'track')
        if track_id in tracks:
            fail(f'Duplicate track ID: {track_id}')
        tracks.add(track_id)
        text(track.get('title'), f'{track_id}.title')
        text(track.get('purpose'), f'{track_id}.purpose')
        route = array(track.get('topics'), f'{track_id}.topics')
        if not route:
            fail(f'{track_id}: empty track')
        route_ids = [tid for tid in route if isinstance(tid, str)]
        if len(set(route_ids)) != len(route_ids):
            fail(f'{track_id}: duplicate route topic')
        for tid in route:
            if not isinstance(tid, str) or tid not in topics:
                fail(f'{track_id}: unknown topic {tid}')
    return errors, labs


def local_links():
    """Check ordinary Markdown file links; skip fences, URLs, and fragments."""
    errors = []
    files = list(ROOT.glob('*.md'))
    for folder in ['docs', 'catalog', 'templates', 'domains', 'projects', 'experiments', '.agent']:
        files.extend((ROOT / folder).rglob('*.md'))
    for source in files:
        # Installed dependencies own their documentation; published packages may
        # omit files linked by it. Validate authored repository docs only.
        if 'node_modules' in source.relative_to(ROOT).parts:
            continue
        content = source.read_text(encoding='utf-8')
        content = re.sub(r'```.*?```', '', content, flags=re.S)
        content = re.sub(r'`[^`]*`', '', content)
        for match in re.finditer(r'\[[^\]]+\]\(([^)]+)\)', content):
            raw = match.group(1).strip()
            if raw.startswith('<') and raw.endswith('>'):
                raw = raw[1:-1]
            url = urlsplit(raw)
            if url.scheme or url.netloc or not url.path:
                continue
            target = (source.parent / unquote(url.path)).resolve()
            if not target.is_relative_to(ROOT) or not target.exists():
                errors.append(f'{source.relative_to(ROOT)}: missing or external local target {raw}')
    return errors


def relative(target, output):
    return Path(os.path.relpath(ROOT / target, (ROOT / output).parent)).as_posix()


def outputs(data, labs):
    topics = {t['id']: t for t in data['topics']}

    def link(tid, output):
        topic = topics[tid]
        target = f"{topic['path']}/README.md" if topic['status'] != 'planned' else f'INDEX.md#{tid}'
        if '#' in target:
            file, fragment = target.split('#')
            url = relative(file, output) + '#' + fragment
        else:
            url = relative(target, output)
        return f"[{topic['title']}]({url})"

    def links(ids, output):
        return ', '.join(link(tid, output) for tid in ids) or '—'

    index = [HEADER, '# Topic index', '',
             f"{len(topics)} mapped topics across {len(data['domains'])} domains. "
             f"{sum(t['status'] != 'planned' for t in topics.values())} topics have starter content. "
             'Planned entries name intended homes; they are not existing implementations.', '',
             '[Interactive graph](interactive/atlas.html) · [Learning paths](docs/LEARNING-PATHS.md) · '
             '[Taxonomy](docs/TAXONOMY.md) · [Design](docs/DESIGN.md)', '']
    taxonomy = [HEADER, '# Computer engineering taxonomy', '',
                'Groups organize browsing; topics have one canonical home. Planned homes are catalog entries, '
                'not empty folders. This is an extensible map rather than a fixed curriculum.', '']
    for domain in data['domains']:
        did = domain['id']
        index += [f"## {domain['title']}", '', domain['purpose'], '',
                  '| Topic | Status | Entry prerequisites | Lab |', '| --- | --- | --- | --- |']
        taxonomy += [f"## {domain['title']}", '', domain['purpose'], '', f"Canonical prefix: `domains/{did}/`.", '']
        for group in domain['groups']:
            taxonomy += [f"### {group['title']}", '']
            for topic in data['topics']:
                if topic['domain'] != did or topic['group'] != group['id']:
                    continue
                tid = topic['id']
                label = link(tid, 'INDEX.md') if topic['status'] != 'planned' else topic['title']
                lab_links = ', '.join(f"[{lab['title']}]({lab['entry']})" for lab in labs if lab['topic'] == tid) or '—'
                index += [f"| <a id=\"{tid}\"></a>{label} (`{tid}`) | {topic['status']} | {links(topic['prerequisites'], 'INDEX.md')} | {lab_links} |"]
                taxonomy += [f"- {link(tid, 'docs/TAXONOMY.md')} — `{tid}` ({topic['status']})."]
            taxonomy += ['']
        index += ['']
    paths = [HEADER, '# Learning paths and topic milestones', '',
             'These routes follow questions rather than enforce a course sequence. Entry prerequisites are shown '
             'at each stop; fill a gap when needed. Available artifacts are not verified learner outcomes.', '']
    for track in data['tracks']:
        paths += [f"## {track['title']}", '', track['purpose'], '',
                  '| Stop | Topic | Entry prerequisites | Content status |', '| --- | --- | --- | --- |']
        for i, tid in enumerate(track['topics'], 1):
            topic = topics[tid]
            paths += [f"| {i} | {link(tid, 'docs/LEARNING-PATHS.md')} | {links(topic['prerequisites'], 'docs/LEARNING-PATHS.md')} | {topic['status']} |"]
        paths += ['']
    paths += ['## Evidence milestones', '', 'Levels are optional lenses; they are not required folder names.', '']
    for topic in data['topics']:
        if not topic.get('milestones'):
            continue
        paths += [f"### {topic['title']}", '', link(topic['id'], 'docs/LEARNING-PATHS.md'), '',
                  '| Level | Outcome | State | Artifacts |', '| --- | --- | --- | --- |']
        for milestone in sorted(topic['milestones'], key=lambda m: m['level']):
            level = milestone['level']
            artifacts = ', '.join(f"[{Path(a).name}]({relative(a, 'docs/LEARNING-PATHS.md')})" for a in milestone['artifacts']) or '—'
            paths += [f"| {level} — {LEVELS[level]} | {milestone['outcome']} | {milestone['state']} | {artifacts} |"]
        paths += ['']
    payload = json.dumps({**data, 'labEntries': labs}, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')
    shell = (ROOT / 'templates/atlas.html').read_text(encoding='utf-8')
    if shell.count('__CATALOG_JSON__') != 1:
        raise ValueError('Atlas template must contain one __CATALOG_JSON__ marker')
    return {
        'INDEX.md': '\n'.join(index).rstrip() + '\n',
        'docs/TAXONOMY.md': '\n'.join(taxonomy).rstrip() + '\n',
        'docs/LEARNING-PATHS.md': '\n'.join(paths).rstrip() + '\n',
        'interactive/atlas.html': shell.replace('__CATALOG_JSON__', payload),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    commands.add_parser('build', help='Render navigational views from catalog metadata')
    check = commands.add_parser('check', help='Validate metadata, manifests, and local Markdown file links')
    check.add_argument('--generated', action='store_true', help='Also reject stale generated files')
    topic = commands.add_parser('topic', help='Show the maintained metadata for one topic')
    topic.add_argument('id')
    args = parser.parse_args()
    try:
        data = load_catalog()
        errors, labs = validate(data)
        if not errors and args.command == 'build':
            for name, content in outputs(data, labs).items():
                target = ROOT / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding='utf-8')
                print(f'Generated {name}')
        if args.command in ('check', 'build'):
            errors.extend(local_links())
        if not errors and args.command == 'check' and args.generated:
            for name, expected in outputs(data, labs).items():
                target = ROOT / name
                if not target.is_file() or target.read_text(encoding='utf-8') != expected:
                    errors.append(f'Stale generated output: {name}; run python3 scripts/lab.py build')
        if errors:
            for error in errors:
                print('ERROR: ' + error, file=sys.stderr)
            return 1
        if args.command == 'topic':
            selected = next((t for t in data['topics'] if t['id'] == args.id), None)
            if selected is None:
                print(f'Unknown topic: {args.id}', file=sys.stderr)
                return 1
            print(json.dumps(selected, ensure_ascii=False, indent=2))
        else:
            print(f"OK: {len(data['topics'])} topics, {len(data['domains'])} domains, {len(labs)} labs; metadata and local file links valid.")
        return 0
    except (OSError, ValueError) as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
