// Synthetic local IdP fixtures, signed by xml-crypto. Not an authentication server.
import {SignedXml} from 'xml-crypto';import {execFileSync} from 'node:child_process';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
export function ephemeralCertificate(){const dir=mkdtempSync(join(tmpdir(),'iam-saml-'));try{execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',join(dir,'key.pem'),'-out',join(dir,'cert.pem'),'-subj','/CN=local-iam-learning-only','-days','1'],{stdio:'ignore'});return {key:readFileSync(join(dir,'key.pem'),'utf8'),cert:readFileSync(join(dir,'cert.pem'),'utf8')};}finally{rmSync(dir,{recursive:true,force:true});}}
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export function signedResponse({requestId,key,cert,recipient='http://127.0.0.1:3000/saml/acs',audience='urn:iam-lab:sp',subject='alice',issuer='urn:iam-lab:idp',expires=Date.now()+60000}){
 const now=new Date().toISOString(),until=new Date(expires).toISOString(),id='_'+crypto.randomUUID();
 const signElement=(xml,name)=>{const signature=new SignedXml({privateKey:key,publicCert:cert});signature.signatureAlgorithm='http://www.w3.org/2001/04/xmldsig-more#rsa-sha256';signature.canonicalizationAlgorithm='http://www.w3.org/2001/10/xml-exc-c14n#';signature.addReference({xpath:`//*[local-name()='${name}']`,transforms:['http://www.w3.org/2000/09/xmldsig#enveloped-signature','http://www.w3.org/2001/10/xml-exc-c14n#'],digestAlgorithm:'http://www.w3.org/2001/04/xmlenc#sha256'});signature.computeSignature(xml,{location:{reference:`//*[local-name()='${name}']/*[local-name()='Issuer']`,action:'after'}});return signature.getSignedXml();};
 let assertion=`<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="${id}" Version="2.0" IssueInstant="${now}"><saml:Issuer>${escape(issuer)}</saml:Issuer><saml:Subject><saml:NameID>${escape(subject)}</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="${escape(requestId)}" Recipient="${escape(recipient)}" NotOnOrAfter="${until}"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="${new Date(Date.now()-1000).toISOString()}" NotOnOrAfter="${until}"><saml:AudienceRestriction><saml:Audience>${escape(audience)}</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="${now}"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement></saml:Assertion>`;
 assertion=signElement(assertion,'Assertion');
 const response=`<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_${crypto.randomUUID()}" Version="2.0" IssueInstant="${now}" Destination="${escape(recipient)}" InResponseTo="${escape(requestId)}"><saml:Issuer>${escape(issuer)}</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>${assertion}</samlp:Response>`;
 return Buffer.from(signElement(response,'Response')).toString('base64');
}
