import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {secret,equal,digest} from '../../domains/identity-access-management/iam-first-principles/01-cryptography/src/model.mjs';
import {hashPassword,verifyPassword} from '../../domains/identity-access-management/iam-first-principles/02-password-authentication/src/model.mjs';
import {Sessions} from '../../domains/identity-access-management/iam-first-principles/03-session-authentication/src/model.mjs';
import {cookie,csrfAllowed} from '../../domains/identity-access-management/iam-first-principles/04-cookie-security/src/model.mjs';
import {decide} from '../../domains/identity-access-management/iam-first-principles/05-authorization/src/model.mjs';
import {keys,issue,validate,createLocalJWKSet} from '../../domains/identity-access-management/iam-first-principles/07-jwt/src/model.mjs';
import {publicJwk} from '../../domains/identity-access-management/iam-first-principles/08-jwks-and-key-rotation/src/model.mjs';
import {Codes} from '../../domains/identity-access-management/iam-first-principles/09-oauth-authorization-code/src/model.mjs';
import {challengeOf} from '../../domains/identity-access-management/iam-first-principles/10-pkce/src/model.mjs';
import {connect,begin,finish} from '../../domains/identity-access-management/iam-first-principles/11-oidc-relying-party/src/model.mjs';
import {RefreshFamilies} from '../../domains/identity-access-management/iam-first-principles/14-token-revocation/src/model.mjs';
import {Scim,schemas} from '../../domains/identity-access-management/iam-first-principles/19-scim-provisioning/src/model.mjs';
import {Audit} from '../../domains/identity-access-management/iam-first-principles/21-audit-logging/src/model.mjs';

export async function createApp({origin='http://127.0.0.1:3000',clock=()=>Math.floor(Date.now()/1000),scimKey=secret(),issuer='http://127.0.0.1:3001',saml=null}={}){
 const originUrl=new URL(origin);if(!['127.0.0.1','localhost'].includes(originUrl.hostname))throw new Error('educational app is loopback-only');
 const sessions=new Sessions(),refresh=new RefreshFamilies(),audit=new Audit(secret()),users=new Map(),memberships=[],documents=new Map(),external=new Map(),loginTransactions=new Map(),attempts=new Map(),scimLinks=new Map(),platformAdmins=new Set(['alice']);
 let signing=await keys(),kid='k1',publicKeys=[await publicJwk(signing.publicKey,kid)];
 const codeStore=new Codes(new Map([['lab-client',{redirects:[`${origin}/callback`],scopes:['document:read']}]]));
 const refreshContexts=new Map();
 for(const [id,tenant,role] of [['alice','a','owner'],['bob','b','viewer']]){users.set(id,{id,email:`${id}@example.invalid`,active:true,password:await hashPassword('example-only long passphrase')});memberships.push({userId:id,tenant,role,active:true});documents.set(`doc-${tenant}`,{id:`doc-${tenant}`,tenant,title:`Private document ${tenant.toUpperCase()}`});external.set(`${issuer}\nalice`, 'alice');}
 const scim=new Scim((tenant,id)=>{const userId=scimLinks.get(`${tenant}:${id}`);if(userId){for(const m of memberships)if(m.userId===userId&&m.tenant===tenant)m.active=false;sessions.revokeUser(userId);refresh.revokeUser(userId);}});
 const tokenCookie=q=>{const prefix=originUrl.protocol==='https:'?'__Host-iam=':'iam=';return q.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(prefix))?.slice(prefix.length)??'';};
 const log=(event,actor,outcome,extra={})=>audit.append({time:clock(),event,actor,outcome,...extra});
 const send=(r,status,data,headers={})=>{r.writeHead(status,{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff',...headers});r.end(JSON.stringify(data));};
 const redirect=(r,url,headers={})=>{r.writeHead(303,{location:String(url),'cache-control':'no-store',...headers});r.end();};
 async function body(q){let text='';for await(const chunk of q){text+=chunk;if(Buffer.byteLength(text)>65536)throw Object.assign(new Error('body limit'),{status:413});}if((q.headers['content-type']??'').startsWith('application/x-www-form-urlencoded'))return Object.fromEntries(new URLSearchParams(text));return text?JSON.parse(text):{};}
 function session(q){return sessions.resolve(tokenCookie(q),clock());}
 function requireCsrf(q,s){if(!s||!csrfAllowed({origin:q.headers.origin,expectedOrigin:origin,provided:q.headers['x-csrf-token'],session:s}))throw Object.assign(new Error('CSRF rejected'),{status:403});}
 async function mint(userId,tenant,scopes){return issue(signing.privateKey,{issuer:origin,audience:'urn:iam-lab:docs',subject:userId,now:clock(),kid,ttl:60,extra:{tenant,scope:scopes.join(' ')}});}
 async function handler(q,r){const requestId=crypto.randomUUID();r.setHeader('x-request-id',requestId);
 try{
 const url=new URL(q.url,origin),path=url.pathname,s=session(q),user=s&&users.get(s.userId);
 if(path==='/'&&q.method==='GET'){r.writeHead(200,{'content-type':'text/html','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'cache-control':'no-store'});return r.end(await readFile(new URL('./index.html',import.meta.url)));}
 if(path==='/app.js'&&q.method==='GET'){r.writeHead(200,{'content-type':'text/javascript'});return r.end(await readFile(new URL('./app.js',import.meta.url)));}
 if(path==='/register'&&q.method==='POST'){if(q.headers.origin!==origin)throw Object.assign(new Error('origin rejected'),{status:403});const b=await body(q);if(typeof b.email!=='string'||!/^[^\s@]+@[^\s@]+$/.test(b.email)||[...users.values()].some(u=>u.email.toLowerCase()===b.email.toLowerCase()))throw Object.assign(new Error('invalid registration'),{status:400});const id=crypto.randomUUID(),password=await hashPassword(b.password);users.set(id,{id,email:b.email,active:true,password});log('registration',id,'allow');return send(r,201,{id,notice:'No tenant access until an authorized invitation/provisioning assignment.'});}
 if(path==='/login'&&q.method==='POST'){
 if(q.headers.origin!==origin)throw Object.assign(new Error('origin rejected'),{status:403});const b=await body(q),account=String(b.email??'').toLowerCase(),bucketKey=`${q.socket.remoteAddress}:${account}`,bucket=attempts.get(bucketKey)??{start:clock(),count:0};if(clock()-bucket.start>=60){bucket.start=clock();bucket.count=0;}bucket.count++;attempts.set(bucketKey,bucket);if(bucket.count>5)return send(r,429,{error:'try later'});
 const u=[...users.values()].find(x=>x.email.toLowerCase()===account),dummy=users.get('alice').password;const valid=await verifyPassword(b.password,u?.password??dummy);
 if(!u?.active||!u.password||!valid){log('login',u?.id??'unknown','deny');return send(r,401,{error:'invalid credentials'});}const t=sessions.issue(u.id,clock(),tokenCookie(q));log('login',u.id,'allow');return send(r,200,{userId:u.id},{'set-cookie':cookie(t,{secure:originUrl.protocol==='https:'})});}
 if(path==='/me'&&q.method==='GET'){if(!user?.active)return send(r,401,{error:'login required'});return send(r,200,{id:user.id,csrf:s.csrf,memberships:memberships.filter(m=>m.userId===user.id&&m.active)});}
 if(path==='/logout'&&q.method==='POST'){requireCsrf(q,s);sessions.revoke(tokenCookie(q));log('logout',s.userId,'allow');return send(r,200,{loggedOut:true},{'set-cookie':`${cookie('',{secure:originUrl.protocol==='https:'})}; Max-Age=0`});}
 if(path.startsWith('/api/documents/')&&q.method==='GET'){
 let principal=user,tenant=url.searchParams.get('tenant'),scopes=null;
 if(q.headers.authorization){const match=/^Bearer (\S+)$/.exec(q.headers.authorization);if(!match)return send(r,401,{error:'invalid bearer'});try{const {payload}=await validate(match[1],createLocalJWKSet({keys:publicKeys}),{issuer:origin,audience:'urn:iam-lab:docs',now:clock()});principal=users.get(payload.sub);scopes=String(payload.scope??'').split(' ');if(tenant!==payload.tenant)return send(r,403,{error:'token tenant mismatch'});}catch{return send(r,401,{error:'invalid access token'});}}
 const resource=documents.get(path.split('/').at(-1)),decision=decide({principal,resource,action:'document:read',tenant,memberships});if(scopes&&!scopes.includes('document:read'))decision.allow=false;log('authorization',principal?.id??'anonymous',decision.allow?'allow':'deny',{tenant,resource:resource?.id,action:'document:read',reason:decision.reason,requestId});return decision.allow?send(r,200,resource):send(r,principal?404:401,{error:'resource unavailable'});}
 if(path==='/authorize'&&q.method==='POST'){requireCsrf(q,s);if(!user?.active)return send(r,401,{error:'inactive'});const b=await body(q),tenant=b.tenant;if(!memberships.some(m=>m.userId===user.id&&m.tenant===tenant&&m.active))return send(r,403,{error:'no membership'});const scopes=String(b.scope??'').split(' '),code=codeStore.authorize({clientId:b.client_id,redirectUri:b.redirect_uri,subject:user.id,scopes,challenge:b.code_challenge,method:b.code_challenge_method,now:clock(),consent:b.consent===true});codeStore.rows.get(digest(code)).tenant=tenant;return send(r,200,{code,state:b.state});}
 if(path==='/token'&&q.method==='POST'){const b=await body(q);let sub,tenant,scopes,rt;
 if(b.grant_type==='authorization_code'){const grant=codeStore.redeem({code:b.code,clientId:b.client_id,redirectUri:b.redirect_uri,verifier:b.code_verifier,challengeOf,now:clock()});sub=grant.subject;const record=codeStore.rows.get(digest(b.code));tenant=record.tenant;scopes=grant.scopes;rt=refresh.issue({subject:sub,clientId:b.client_id,now:clock()});refreshContexts.set(digest(rt),{sub,tenant,scopes});}
 else if(b.grant_type==='refresh_token'){const context=refreshContexts.get(digest(b.refresh_token??''));if(!context)throw new Error('invalid_grant');({sub,tenant,scopes}=context);rt=refresh.rotate(b.refresh_token,b.client_id,clock());refreshContexts.set(digest(rt),context);}else return send(r,400,{error:'unsupported_grant_type'});
 if(!users.get(sub)?.active||!memberships.some(m=>m.userId===sub&&m.tenant===tenant&&m.active)){refresh.revoke(rt);return send(r,400,{error:'invalid_grant'});}log('token issuance',sub,'allow',{tenant});return send(r,200,{access_token:await mint(sub,tenant,scopes),refresh_token:rt,token_type:'Bearer',expires_in:60});}
 if(path==='/revoke'&&q.method==='POST'){const b=await body(q);refresh.revoke(b.token);return send(r,200,{});}
 if(path==='/jwks'&&q.method==='GET')return send(r,200,{keys:publicKeys});
 if(path==='/admin/rotate'&&q.method==='POST'){requireCsrf(q,s);if(!user?.active||!platformAdmins.has(user.id))return send(r,403,{error:'platform administrator required'});signing=await keys();kid=crypto.randomUUID();publicKeys.push(await publicJwk(signing.publicKey,kid));log('key rotation',user.id,'allow');return send(r,200,{kid});}
 if(path.startsWith('/scim/v2/')){
 const auth=/^Bearer (\S+)$/.exec(q.headers.authorization??'');if(!auth||!equal(auth[1],scimKey))return send(r,401,{error:'connector credential required'});const tenant='a';// This connector credential is bound to tenant A; request cannot choose another tenant.
 const parts=path.split('/'),kind=parts[3]==='Users'?'User':parts[3]==='Groups'?'Group':null,id=parts[4];if(!kind)return send(r,404,{error:'unknown resource'});let data,status=200;
 if(q.method==='GET')data=id?scim.get(tenant,kind,id):scim.list(tenant,kind,Object.fromEntries(url.searchParams));
 else if(q.method==='POST'&&!id){const input=await body(q);data=scim.create(tenant,kind,input);status=201;if(kind==='User'){const userId=crypto.randomUUID();users.set(userId,{id:userId,email:input.userName,active:true,password:null});memberships.push({userId,tenant,role:'viewer',active:data.active});scimLinks.set(`${tenant}:${data.id}`,userId);}}
 else if(q.method==='PATCH'&&id)data=scim.patch(tenant,kind,id,await body(q),q.headers['if-match']);else return send(r,405,{error:'unsupported method'});
 log('provisioning','scim-connector','allow',{tenant,resource:data.id});return send(r,status,data,{'content-type':'application/scim+json',...(data.meta?{etag:data.meta.version,location:`${origin}/scim/v2/${kind==='User'?'Users':'Groups'}/${data.id}`}:{})});}
 if(path==='/oidc/login'&&q.method==='GET'){const config=await connect(issuer),start=await begin(config,`${origin}/oidc/callback`),handle=secret();loginTransactions.set(handle,{...start.transaction,config});return redirect(r,start.url,{'set-cookie':`oidc_tx=${handle}; Path=/oidc; HttpOnly; SameSite=Lax; Max-Age=300`});}
 if(path==='/oidc/callback'&&q.method==='GET'){const handle=q.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('oidc_tx='))?.slice(8),tx=loginTransactions.get(handle);loginTransactions.delete(handle);const identity=await finish(tx?.config,url,tx),id=external.get(`${identity.issuer}\n${identity.subject}`);if(!id||!users.get(id)?.active)return send(r,403,{error:'federated identity has no active linked account'});const token=sessions.issue(id,clock(),tokenCookie(q));log('federated login',id,'allow');return redirect(r,'/',{'set-cookie':[cookie(token,{secure:originUrl.protocol==='https:'}),'oidc_tx=; Path=/oidc; HttpOnly; SameSite=Lax; Max-Age=0']});}
 if(path==='/saml/login'&&q.method==='GET'&&saml){const relay=secret();loginTransactions.set(relay,{created:Date.now(),saml:true});return redirect(r,await saml.getAuthorizeUrlAsync(relay,undefined,{}),{'set-cookie':`saml_tx=${relay}; Path=/saml; HttpOnly; SameSite=None; Secure; Max-Age=300`});}
 if(path==='/saml/acs'&&q.method==='POST'&&saml){const b=await body(q),relay=b.RelayState,tx=loginTransactions.get(relay),bound=q.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('saml_tx='))?.slice(8);loginTransactions.delete(relay);if(!tx?.saml||Date.now()-tx.created>300000||!equal(bound??'',relay??''))return send(r,403,{error:'SAML browser transaction mismatch (HTTPS required)'});const {consume}=await import('../../domains/identity-access-management/iam-first-principles/18-saml-sso/src/model.mjs'),p=await consume(saml,b.SAMLResponse);const id=external.get(`urn:iam-lab:idp\n${p.nameID}`);if(!id||!users.get(id)?.active)return send(r,403,{error:'unlinked identity'});return redirect(r,'/',{'set-cookie':cookie(sessions.issue(id,clock(),tokenCookie(q)),{secure:true})});}
 return send(r,404,{error:'unknown route'});
 }catch(e){log('request failure','unknown','deny',{requestId,reason:e.status?'request rejected':'validation failed'});const status=e.status??400;return send(r,status,e.status&&String(q.url).startsWith('/scim/')?{schemas:[schemas.Error],status:String(status),detail:e.message,...(e.scimType?{scimType:e.scimType}:{})}:{error:e.status?e.message:'request validation failed'});}
 }
 const server=createServer(handler);return {server,users,memberships,sessions,refresh,scim,scimLinks,audit,mint,scimKey,codeStore,external};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const app=await createApp({scimKey:process.env.IAM_SCIM_KEY??'example-only-local-scim-key'});app.server.listen(3000,'127.0.0.1',()=>console.log('IAM learning app: http://127.0.0.1:3000; state and keys are ephemeral.'));}
