import test from 'node:test';
import assert from 'node:assert/strict';

import {createApp} from '../src/model.mjs';import {verifier,challengeOf} from '../../10-pkce/src/model.mjs';
test('HTTP login, CSRF, tenant authorization, code/refresh flow, key rotation, provisioning and logout',async()=>{const app=await createApp({clock:()=>1000,scimKey:'example-only-test-connector'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`,origin='http://127.0.0.1:3000';let cookies='',csrf;async function call(path,{method='GET',data,headers={}}={}){const r=await fetch(base+path,{method,headers:{origin,'content-type':'application/json',...(cookies?{cookie:cookies}:{}),...(csrf?{'x-csrf-token':csrf}:{}),...headers},...(data?{body:JSON.stringify(data)}:{})});const c=r.headers.get('set-cookie');if(c)cookies=c.split(';')[0];return {status:r.status,data:await r.json()};}
try{assert.equal((await call('/me')).status,401);assert.equal((await call('/login',{method:'POST',data:{email:'alice@example.invalid',password:'wrong'}})).status,401);assert.equal((await call('/login',{method:'POST',data:{email:'alice@example.invalid',password:'example-only long passphrase'}})).status,200);csrf=(await call('/me')).data.csrf;assert.equal((await call('/api/documents/doc-a?tenant=a')).status,200);assert.equal((await call('/api/documents/doc-b?tenant=b')).status,404);assert.equal((await call('/logout',{method:'POST',data:{},headers:{origin:'https://evil.invalid'}})).status,403);
const v=verifier(),code=(await call('/authorize',{method:'POST',data:{client_id:'lab-client',redirect_uri:origin+'/callback',scope:'document:read',tenant:'a',code_challenge:challengeOf(v),code_challenge_method:'S256',state:'test-state',consent:true}})).data.code;assert.ok(code);const token=(await call('/token',{method:'POST',data:{grant_type:'authorization_code',code,client_id:'lab-client',redirect_uri:origin+'/callback',code_verifier:v}})).data;assert.ok(token.access_token);assert.equal((await call('/api/documents/doc-a?tenant=a',{headers:{authorization:'Bearer '+token.access_token}})).status,200);await call('/admin/rotate',{method:'POST',data:{}});assert.equal((await call('/api/documents/doc-a?tenant=a',{headers:{authorization:'Bearer '+token.access_token}})).status,200);const next=await call('/token',{method:'POST',data:{grant_type:'refresh_token',client_id:'lab-client',refresh_token:token.refresh_token}});assert.equal(next.status,200);assert.equal((await call('/token',{method:'POST',data:{grant_type:'refresh_token',client_id:'lab-client',refresh_token:token.refresh_token}})).status,400);assert.equal((await call('/token',{method:'POST',data:{grant_type:'refresh_token',client_id:'lab-client',refresh_token:next.data.refresh_token}})).status,400);
app.memberships.find(m=>m.userId==='alice').active=false;assert.equal((await call('/api/documents/doc-a?tenant=a',{headers:{authorization:'Bearer '+token.access_token}})).status,404);app.memberships[0].active=true;
const scimHeaders={authorization:'Bearer example-only-test-connector'};assert.equal((await call('/scim/v2/Users')).status,401);const provisioned=await call('/scim/v2/Users',{method:'POST',headers:scimHeaders,data:{schemas:['urn:ietf:params:scim:schemas:core:2.0:User'],userName:'new@example.invalid'}});assert.equal(provisioned.status,201);const deactivated=await call('/scim/v2/Users/'+provisioned.data.id,{method:'PATCH',headers:scimHeaders,data:{schemas:['urn:ietf:params:scim:api:messages:2.0:PatchOp'],Operations:[{op:'replace',path:'active',value:false}]}});assert.equal(deactivated.data.active,false);assert.equal(app.memberships.at(-1).active,false);
assert.equal((await call('/logout',{method:'POST',data:{}})).status,200);assert.equal((await call('/me')).status,401);// A provisioning-only account has no enrolled password, including the fixture password.
assert.equal((await call('/login',{method:'POST',data:{email:'new@example.invalid',password:'example-only long passphrase'}})).status,401);
// Tenant ownership is not issuer-wide platform administration.
app.memberships.find(m=>m.userId==='bob').role='owner';
assert.equal((await call('/login',{method:'POST',data:{email:'bob@example.invalid',password:'example-only long passphrase'}})).status,200);csrf=(await call('/me')).data.csrf;
assert.equal((await call('/admin/rotate',{method:'POST',data:{}})).status,403);
for(let i=0;i<5;i++)assert.equal((await call('/login',{method:'POST',data:{email:'unknown@example.invalid',password:'wrong'}})).status,401);
assert.equal((await call('/login',{method:'POST',data:{email:'unknown@example.invalid',password:'wrong'}})).status,429);
assert.equal(app.audit.verify(),true);const logs=JSON.stringify(app.audit.rows);assert.ok(!logs.includes(token.access_token));assert.ok(!logs.includes('example-only long passphrase'));}finally{app.server.closeAllConnections();await new Promise(r=>app.server.close(r));}});
